// <auto-generated />
using System;
using DealershipSystem.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DealershipSystem.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DealershipSystem.Models.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CityRomanized")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<int>("PrefectureId")
                        .HasColumnType("integer");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StreetRomanized")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PrefectureId");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("DealershipSystem.Models.BodyType", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("NameDeutsch")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NameEnglish")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("BodyTypes");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            NameDeutsch = "Kei Car",
                            NameEnglish = "Kei Car"
                        },
                        new
                        {
                            ID = 2,
                            NameDeutsch = "Compact Car",
                            NameEnglish = "Compact Car"
                        },
                        new
                        {
                            ID = 3,
                            NameDeutsch = "Minivan/One-Box",
                            NameEnglish = "Minivan/One-Box"
                        },
                        new
                        {
                            ID = 4,
                            NameDeutsch = "Sedan",
                            NameEnglish = "Sedan"
                        },
                        new
                        {
                            ID = 5,
                            NameDeutsch = "Coupe",
                            NameEnglish = "Coupe"
                        },
                        new
                        {
                            ID = 6,
                            NameDeutsch = "Station Wagon",
                            NameEnglish = "Station Wagon"
                        },
                        new
                        {
                            ID = 7,
                            NameDeutsch = "SUV/Crossover",
                            NameEnglish = "SUV/Crossover"
                        },
                        new
                        {
                            ID = 8,
                            NameDeutsch = "Truck/Van",
                            NameEnglish = "Truck/Van"
                        },
                        new
                        {
                            ID = 9,
                            NameDeutsch = "Hatchback",
                            NameEnglish = "Hatchback"
                        });
                });

            modelBuilder.Entity("DealershipSystem.Models.Car", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("BodyTypeID")
                        .HasColumnType("integer");

                    b.Property<int>("BrandID")
                        .HasColumnType("integer");

                    b.Property<int>("CarModelID")
                        .HasColumnType("integer");

                    b.Property<int>("ColorID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateOfManufacture")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DriveTrainID")
                        .HasColumnType("integer");

                    b.Property<int>("EngineSizeID")
                        .HasColumnType("integer");

                    b.Property<int>("FuelTypeID")
                        .HasColumnType("integer");

                    b.Property<int>("Grade")
                        .HasColumnType("integer");

                    b.Property<bool>("IsInTransfer")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSmoking")
                        .HasColumnType("boolean");

                    b.Property<string>("LicensePlateNumber")
                        .HasColumnType("text");

                    b.Property<int>("LocationID")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("MOTExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Mileage")
                        .HasColumnType("integer");

                    b.Property<int>("ModelID")
                        .HasColumnType("integer");

                    b.Property<string>("Price")
                        .HasColumnType("text");

                    b.Property<bool>("RepairHistory")
                        .HasColumnType("boolean");

                    b.Property<int>("TransmissionTypeID")
                        .HasColumnType("integer");

                    b.Property<string>("VINNum")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.HasIndex("BodyTypeID");

                    b.HasIndex("BrandID");

                    b.HasIndex("CarModelID");

                    b.HasIndex("ColorID");

                    b.HasIndex("DriveTrainID");

                    b.HasIndex("EngineSizeID");

                    b.HasIndex("FuelTypeID");

                    b.HasIndex("LocationID");

                    b.HasIndex("TransmissionTypeID");

                    b.ToTable("Cars");
                });

            modelBuilder.Entity("DealershipSystem.Models.CarExtra", b =>
                {
                    b.Property<int>("CarExtraID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CarExtraID"));

                    b.Property<int>("CarID")
                        .HasColumnType("integer");

                    b.Property<int>("ExtraID")
                        .HasColumnType("integer");

                    b.HasKey("CarExtraID");

                    b.HasIndex("CarID");

                    b.HasIndex("ExtraID");

                    b.ToTable("CarExtras");
                });

            modelBuilder.Entity("DealershipSystem.Models.CarMaker", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("BrandDeutsch")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BrandEnglish")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("CarMakers");
                });

            modelBuilder.Entity("DealershipSystem.Models.CarModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("Height")
                        .HasColumnType("integer");

                    b.Property<int>("Length")
                        .HasColumnType("integer");

                    b.Property<int>("MakerID")
                        .HasColumnType("integer");

                    b.Property<int>("ManufacturingEndYear")
                        .HasColumnType("integer");

                    b.Property<int>("ManufacturingStartYear")
                        .HasColumnType("integer");

                    b.Property<int>("Mass")
                        .HasColumnType("integer");

                    b.Property<string>("ModelCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ModelNameDeutsch")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ModelNameEnglish")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("PassengerCount")
                        .HasColumnType("integer");

                    b.Property<int>("Width")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("MakerID");

                    b.ToTable("CarModels");
                });

            modelBuilder.Entity("DealershipSystem.Models.Color", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("ColorNameDeutsch")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ColorNameEnglish")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Colors");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            ColorNameDeutsch = "White",
                            ColorNameEnglish = "White"
                        },
                        new
                        {
                            ID = 2,
                            ColorNameDeutsch = "Black",
                            ColorNameEnglish = "Black"
                        },
                        new
                        {
                            ID = 3,
                            ColorNameDeutsch = "Red",
                            ColorNameEnglish = "Red"
                        },
                        new
                        {
                            ID = 4,
                            ColorNameDeutsch = "Blue",
                            ColorNameEnglish = "Blue"
                        },
                        new
                        {
                            ID = 5,
                            ColorNameDeutsch = "Silver",
                            ColorNameEnglish = "Silver"
                        },
                        new
                        {
                            ID = 6,
                            ColorNameDeutsch = "Gray",
                            ColorNameEnglish = "Gray"
                        },
                        new
                        {
                            ID = 7,
                            ColorNameDeutsch = "Gold",
                            ColorNameEnglish = "Gold"
                        },
                        new
                        {
                            ID = 8,
                            ColorNameDeutsch = "Beige",
                            ColorNameEnglish = "Beige"
                        },
                        new
                        {
                            ID = 9,
                            ColorNameDeutsch = "Brown",
                            ColorNameEnglish = "Brown"
                        },
                        new
                        {
                            ID = 10,
                            ColorNameDeutsch = "Orange",
                            ColorNameEnglish = "Orange"
                        },
                        new
                        {
                            ID = 11,
                            ColorNameDeutsch = "Pink",
                            ColorNameEnglish = "Pink"
                        },
                        new
                        {
                            ID = 12,
                            ColorNameDeutsch = "Purple",
                            ColorNameEnglish = "Purple"
                        },
                        new
                        {
                            ID = 13,
                            ColorNameDeutsch = "Yellow",
                            ColorNameEnglish = "Yellow"
                        },
                        new
                        {
                            ID = 14,
                            ColorNameDeutsch = "Green",
                            ColorNameEnglish = "Green"
                        },
                        new
                        {
                            ID = 15,
                            ColorNameDeutsch = "Other",
                            ColorNameEnglish = "Other"
                        });
                });

            modelBuilder.Entity("DealershipSystem.Models.DrivetrainType", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("DrivetrainTypes");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Type = "FWD"
                        },
                        new
                        {
                            ID = 2,
                            Type = "RWD"
                        },
                        new
                        {
                            ID = 3,
                            Type = "AWD"
                        },
                        new
                        {
                            ID = 4,
                            Type = "4WD"
                        });
                });

            modelBuilder.Entity("DealershipSystem.Models.EmployeeLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<int>("LocationId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.ToTable("EmployeeLocations");
                });

            modelBuilder.Entity("DealershipSystem.Models.EngineSizeModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("EngineSize")
                        .HasColumnType("integer");

                    b.Property<int>("FuelTypeID")
                        .HasColumnType("integer");

                    b.Property<int>("ModelID")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("FuelTypeID");

                    b.HasIndex("ModelID");

                    b.ToTable("EngineSizeModels");
                });

            modelBuilder.Entity("DealershipSystem.Models.FuelType", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("NameDeutsch")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NameEnglish")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("FuelTypes");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            NameDeutsch = "Gasoline",
                            NameEnglish = "Gasoline"
                        },
                        new
                        {
                            ID = 2,
                            NameDeutsch = "Diesel",
                            NameEnglish = "Diesel"
                        },
                        new
                        {
                            ID = 3,
                            NameDeutsch = "Hybrid",
                            NameEnglish = "Hybrid"
                        },
                        new
                        {
                            ID = 4,
                            NameDeutsch = "Electric",
                            NameEnglish = "Electric"
                        },
                        new
                        {
                            ID = 5,
                            NameDeutsch = "LPG",
                            NameEnglish = "LPG"
                        });
                });

            modelBuilder.Entity("DealershipSystem.Models.Image", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("CarID")
                        .HasColumnType("integer");

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.HasIndex("CarID");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("DealershipSystem.Models.Location", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("AddressId")
                        .HasColumnType("integer");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MaxCapacity")
                        .HasColumnType("integer");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.HasKey("ID");

                    b.HasIndex("AddressId");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("DealershipSystem.Models.Prefecture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("NameDE")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("NameDE")
                        .IsUnique();

                    b.ToTable("Prefectures");

                    b.HasData(
                        new { Id = 1, Name = "Győr-Moson-Sopron", NameDE = "Győr-Moson-Sopron" },
                        new { Id = 4, Name = "Fejér", NameDE = "Fejér" },
                        new { Id = 12, Name = "Budapest", NameDE = "Budapest" },
                        new { Id = 13, Name = "Budapest", NameDE = "Budapest" },
                        new { Id = 14, Name = "Pest", NameDE = "Pest" },
                        new { Id = 23, Name = "Hajdú-Bihar", NameDE = "Hajdú-Bihar" },
                        new { Id = 27, Name = "Budapest", NameDE = "Budapest" },
                        new { Id = 40, Name = "Hajdú-Bihar", NameDE = "Hajdú-Bihar" },
                        new { Id = 47, Name = "Pest", NameDE = "Pest" }
                    );
                });

            modelBuilder.Entity("DealershipSystem.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CarId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("DealershipSystem.Models.SavedCar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CarId")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("SavedCars");
                });

            modelBuilder.Entity("DealershipSystem.Models.TransmissionType", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("TransmissionTypes");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Type = "MT"
                        },
                        new
                        {
                            ID = 2,
                            Type = "AT"
                        },
                        new
                        {
                            ID = 3,
                            Type = "CVT"
                        },
                        new
                        {
                            ID = 4,
                            Type = "AMT"
                        },
                        new
                        {
                            ID = 5,
                            Type = "DCT"
                        });
                });

            modelBuilder.Entity("DealershipSystem.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("PreferredLanguage")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RefreshTokenExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Recipient")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("RoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("UserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("UserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens");
                });

            modelBuilder.Entity("DealershipSystem.Models.Address", b =>
                {
                    b.HasOne("DealershipSystem.Models.Prefecture", "Prefecture")
                        .WithMany()
                        .HasForeignKey("PrefectureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prefecture");
                });

            modelBuilder.Entity("DealershipSystem.Models.Car", b =>
                {
                    b.HasOne("DealershipSystem.Models.BodyType", "BodyType")
                        .WithMany()
                        .HasForeignKey("BodyTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DealershipSystem.Models.CarMaker", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DealershipSystem.Models.CarModel", "CarModel")
                        .WithMany()
                        .HasForeignKey("CarModelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DealershipSystem.Models.Color", "Color")
                        .WithMany("Cars")
                        .HasForeignKey("ColorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DealershipSystem.Models.DrivetrainType", "DriveTrain")
                        .WithMany()
                        .HasForeignKey("DriveTrainID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DealershipSystem.Models.EngineSizeModel", "EngineSize")
                        .WithMany()
                        .HasForeignKey("EngineSizeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DealershipSystem.Models.FuelType", "FuelType")
                        .WithMany()
                        .HasForeignKey("FuelTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DealershipSystem.Models.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DealershipSystem.Models.TransmissionType", "TransmissionType")
                        .WithMany()
                        .HasForeignKey("TransmissionTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BodyType");

                    b.Navigation("Brand");

                    b.Navigation("CarModel");

                    b.Navigation("Color");

                    b.Navigation("DriveTrain");

                    b.Navigation("EngineSize");

                    b.Navigation("FuelType");

                    b.Navigation("Location");

                    b.Navigation("TransmissionType");
                });

            modelBuilder.Entity("DealershipSystem.Models.CarExtra", b =>
                {
                    b.HasOne("DealershipSystem.Models.Car", "Car")
                        .WithMany("CarExtras")
                        .HasForeignKey("CarID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DealershipSystem.Models.Car", "Extra")
                        .WithMany()
                        .HasForeignKey("ExtraID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("Extra");
                });

            modelBuilder.Entity("DealershipSystem.Models.CarModel", b =>
                {
                    b.HasOne("DealershipSystem.Models.CarMaker", "Maker")
                        .WithMany()
                        .HasForeignKey("MakerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Maker");
                });

            modelBuilder.Entity("DealershipSystem.Models.EmployeeLocation", b =>
                {
                    b.HasOne("DealershipSystem.Models.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("DealershipSystem.Models.EngineSizeModel", b =>
                {
                    b.HasOne("DealershipSystem.Models.FuelType", "FuelType")
                        .WithMany()
                        .HasForeignKey("FuelTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DealershipSystem.Models.CarModel", "CarModel")
                        .WithMany("EngineSizes")
                        .HasForeignKey("ModelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CarModel");

                    b.Navigation("FuelType");
                });

            modelBuilder.Entity("DealershipSystem.Models.Image", b =>
                {
                    b.HasOne("DealershipSystem.Models.Car", "Car")
                        .WithMany("Images")
                        .HasForeignKey("CarID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");
                });

            modelBuilder.Entity("DealershipSystem.Models.Location", b =>
                {
                    b.HasOne("DealershipSystem.Models.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");
                });

            modelBuilder.Entity("DealershipSystem.Models.Car", b =>
                {
                    b.Navigation("CarExtras");

                    b.Navigation("Images");
                });

            modelBuilder.Entity("DealershipSystem.Models.CarModel", b =>
                {
                    b.Navigation("EngineSizes");
                });

            modelBuilder.Entity("DealershipSystem.Models.Color", b =>
                {
                    b.Navigation("Cars");
                });
#pragma warning restore 612, 618
        }
    }
}
